# Generated by Django 6.0.4 on 2026-06-08 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacaoPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='importacoes/%Y/%m/', verbose_name='arquivo PDF')),
                ('status', models.CharField(choices=[('enviado', 'Enviado'), ('processando', 'Processando'), ('concluido', 'Concluído'), ('erro', 'Erro')], default='enviado', max_length=20)),
                ('num_questoes', models.PositiveIntegerField(default=0, verbose_name='questões extraídas')),
                ('confianca_media', models.FloatField(default=0.0, verbose_name='confiança média')),
                ('usou_ia', models.BooleanField(default=False, verbose_name='refinado por IA')),
                ('erro', models.TextField(blank=True, verbose_name='mensagem de erro')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='importacoes', to='exams.disciplina')),
            ],
            options={
                'verbose_name': 'importação de PDF',
                'verbose_name_plural': 'importações de PDF',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(default=0, verbose_name='número')),
                ('enunciado_md', models.TextField(blank=True, verbose_name='enunciado (markdown)')),
                ('gabarito', models.CharField(blank=True, max_length=255, verbose_name='gabarito')),
                ('status', models.CharField(choices=[('em_revisao', 'Em revisão'), ('disponivel', 'Disponível'), ('na_fila', 'Na fila'), ('processando', 'Processando'), ('concluida', 'Concluída'), ('erro', 'Erro')], default='em_revisao', max_length=20)),
                ('confianca_extracao', models.FloatField(default=0.0, verbose_name='confiança da extração')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='exams.disciplina')),
                ('importacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questoes', to='questions.importacaopdf')),
            ],
            options={
                'verbose_name': 'questão',
                'verbose_name_plural': 'questões',
                'ordering': ['ordem', 'numero', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuestaoImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='questoes/%Y/%m/', verbose_name='imagem')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='questions.questao')),
            ],
            options={
                'verbose_name': 'imagem da questão',
                'verbose_name_plural': 'imagens das questões',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
