# Generated by Django 6.0.6 on 2026-06-12 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importacaopdf',
            name='etapa',
            field=models.CharField(blank=True, max_length=120, verbose_name='etapa atual'),
        ),
        migrations.AddField(
            model_name='importacaopdf',
            name='progresso',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='progresso (%)'),
        ),
        migrations.AddField(
            model_name='importacaopdf',
            name='total_paginas',
            field=models.PositiveIntegerField(default=0, verbose_name='total de páginas'),
        ),
    ]
