# Generated by Django 6.0.6 on 2026-07-11 22:23

from django.db import migrations, models


def em_revisao_para_disponivel(apps, schema_editor):
    Questao = apps.get_model('questions', 'Questao')
    Questao.objects.filter(status='em_revisao').update(status='disponivel')


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_importacaopdf_etapa_importacaopdf_progresso_and_more'),
    ]

    operations = [
        migrations.RunPython(em_revisao_para_disponivel, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='questao',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('na_fila', 'Na fila'), ('processando', 'Processando'), ('concluida', 'Concluída'), ('erro', 'Erro')], default='disponivel', max_length=20),
        ),
    ]
