# Generated by Django 6.0.6 on 2026-07-19 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_remove_prova_descricao'),
        ('questions', '0003_alter_questao_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('descricao', models.CharField(blank=True, max_length=500, verbose_name='descrição')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicos', to='exams.disciplina')),
            ],
            options={
                'verbose_name': 'tópico',
                'verbose_name_plural': 'tópicos',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.AddField(
            model_name='questao',
            name='topico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questoes', to='questions.topico'),
        ),
    ]
