# Generated by Django 6.0.6 on 2026-07-20 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_topico_questao_topico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeituraTopico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lido_em', models.DateTimeField(auto_now_add=True, verbose_name='lido em')),
                ('topico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to='questions.topico')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'leitura de tópico',
                'verbose_name_plural': 'leituras de tópicos',
                'constraints': [models.UniqueConstraint(fields=('user', 'topico'), name='leitura_unica_por_topico')],
            },
        ),
    ]
