# Generated by Django 6.0.6 on 2026-07-22 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_leituratopico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RespostaRevisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternativa', models.CharField(max_length=4, verbose_name='alternativa escolhida')),
                ('correta', models.BooleanField(verbose_name='acertou')),
                ('respondido_em', models.DateTimeField(auto_now_add=True, verbose_name='respondido em')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='questions.questao')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_revisao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'resposta de revisão',
                'verbose_name_plural': 'respostas de revisão',
                'ordering': ['-respondido_em'],
            },
        ),
    ]
