# Generated by Django 6.0.8 on 2026-09-10 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_respostarevisao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestaoImagem',
        ),
    ]
