# Generated by Django 6.0.6 on 2026-07-20 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('questions', '0005_leituratopico'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ultimo_topico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='questions.topico', verbose_name='último tópico lido'),
        ),
    ]
