# Generated by Django 6.0.4 on 2026-06-08 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'prova',
                'verbose_name_plural': 'provas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('prova', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='exams.prova')),
            ],
            options={
                'verbose_name': 'disciplina',
                'verbose_name_plural': 'disciplinas',
                'ordering': ['ordem', 'nome'],
            },
        ),
    ]
