# Generated by Django 6.0.6 on 2026-06-11 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prova',
            name='descricao',
        ),
    ]
