# Generated by Django 6.0.6 on 2026-06-11 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='arquivo_md',
            field=models.FileField(blank=True, null=True, upload_to='relatorios/%Y/%m/', verbose_name='Markdown'),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='arquivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='relatorios/%Y/%m/', verbose_name='PDF'),
        ),
    ]
