# Generated by Django 6.0.6 on 2026-07-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_relatorio_arquivo_md_alter_relatorio_arquivo_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='tipo',
            field=models.CharField(choices=[('comentarios', 'Comentários das questões'), ('topicos', 'Tópicos de estudo')], default='comentarios', max_length=20, verbose_name='tipo'),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='num_questoes',
            field=models.PositiveIntegerField(default=0, verbose_name='nº de itens (questões ou tópicos)'),
        ),
    ]
