# Generated by Django 6.0.4 on 2026-06-08 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='nome')),
                ('tipo', models.CharField(choices=[('completo', 'Completo'), ('sucinto', 'Sucinto (revisão)')], default='completo', max_length=20, verbose_name='tipo')),
                ('texto', models.TextField(help_text='Instruções enviadas à IA. O enunciado e o gabarito da questão são anexados automaticamente.', verbose_name='texto do prompt')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'prompt',
                'verbose_name_plural': 'prompts',
                'ordering': ['nome'],
            },
        ),
    ]
