# Generated by Django 6.0.4 on 2026-06-08 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prompts', '0001_initial'),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('concluido', 'Concluído'), ('erro', 'Erro')], default='pendente', max_length=20)),
                ('resultado_md', models.TextField(blank=True, verbose_name='resultado (markdown)')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='modelo')),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('custo_estimado', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('batch_id', models.CharField(blank=True, max_length=120, verbose_name='batch id')),
                ('erro', models.TextField(blank=True, verbose_name='erro')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='prompts.prompt')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='questions.questao')),
            ],
            options={
                'verbose_name': 'resultado de prompt',
                'verbose_name_plural': 'resultados de prompts',
                'ordering': ['-criado_em'],
            },
        ),
    ]
