# Generated by Django 6.0.6 on 2026-07-19 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextoTopico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('concluido', 'Concluído'), ('erro', 'Erro')], default='pendente', max_length=20)),
                ('texto_md', models.TextField(blank=True, verbose_name='texto (markdown)')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='modelo')),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('custo_estimado', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('batch_id', models.CharField(blank=True, max_length=120, verbose_name='batch id')),
                ('erro', models.TextField(blank=True, verbose_name='erro')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'texto de tópico',
                'verbose_name_plural': 'textos de tópicos',
                'ordering': ['topico__ordem', 'topico_id'],
            },
        ),
    ]
