# Generated by Django 6.0.6 on 2026-07-19 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_textotopico'),
        ('questions', '0004_topico_questao_topico'),
    ]

    operations = [
        migrations.AddField(
            model_name='textotopico',
            name='topico',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='texto', to='questions.topico'),
        ),
    ]
