# Generated by Django 6.0.6 on 2026-07-22 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_textotopico_topico'),
        ('exams', '0002_remove_prova_descricao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MentoriaDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_md', models.TextField(blank=True, verbose_name='texto (markdown)')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='modelo')),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('custo_estimado', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorias', to='exams.disciplina')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'mentoria de disciplina',
                'verbose_name_plural': 'mentorias de disciplinas',
                'constraints': [models.UniqueConstraint(fields=('user', 'disciplina'), name='mentoria_unica_por_disciplina')],
            },
        ),
    ]
