# Generated by Django 6.0.6 on 2026-07-22 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_mentoriadisciplina'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mentoriadisciplina',
            name='mentoria_unica_por_disciplina',
        ),
        migrations.DeleteModel(
            name='MentoriaDisciplina',
        ),
    ]
